CREATE TABLE IF NOT EXISTS Player (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(256) DEFAULT NULL,
  age INT DEFAULT NULL,
  description VARCHAR(256),
  img VARCHAR(256) NOT NULL,
  PRIMARY KEY (id)
);