ALTER TABLE Guitar DROP year;
ALTER TABLE Amplifier DROP year;

ALTER TABLE Guitar CHANGE image image VARCHAR(256) DEFAULT NULL;
ALTER TABLE Amplifier CHANGE image image VARCHAR(256) DEFAULT NULL;
ALTER TABLE Effect CHANGE image image VARCHAR(256) DEFAULT NULL;
ALTER TABLE Player CHANGE image image VARCHAR(256) DEFAULT NULL;